resources:
- name: concourse-packer
  type: git
  source:
    uri: https://github.com/jk563/concourse-packer.git
    branch: master

jobs:
- name: create-concourse-amis
  public: true
  plan:
    - get: concourse-packer
      trigger: true
    - task: tester
      config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: busybox }
          run:
            path: ls
