resources:
- name: pipelines
  type: git
  source:
    uri: https://github.com/jk563/pipelines.git
    branch: master

jobs:
- name: apply pipelines
  public: true
  plan:
    - get: pipelines
      trigger: true
    - task: apply
      config: 
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: jk563/fly}
        inputs:
        - name: pipelines
        run:
          dir: pipelines
          path: fly
          
