resource_types:
- name: concourse-pipeline
  type: docker-image
  source:
    repository: concourse/concourse-pipeline-resource

resources:
- name: pipelines
  type: git
  source:
    uri: https://github.com/jk563/pipelines.git
    branch: master
- name: concourse-pipelines
  type: concourse-pipeline
  source:
    insecure: "true"
    teams:
    - name: main
      username: jamie
      password: norbit

jobs:
- name: update-pipelines
  public: true
  plan:
    - get: pipelines
      trigger: true
    - put: concourse-pipelines
      params:
        pipelines:
        - name: Pipelines
          team: main
          config_file: pipelines/core/pipelines.yml
        - name: ContainerFly
          team: main
          config_file: pipelines/other/container-fly.yml

